### ISSUE TITLE
Empty index.js file in node_modules

### ISSUE THREAD

**Issue by sammoh94** [awerlogus/io-ts-transformer#5]
Hi,

I downloaded the package and when I build my code, the index.js file is empty. The index.d.ts file is populated however. In terms of the requirements, I am running `tsc` version 3.7.5 and the io-ts and fp-ts versions are `2.2.1` and `2.5.3`. Any thoughts on what could be the issue. Thanks!

**Comment by awerlogus** [comment]
Can you show me an example of the types you are trying to transform?
Does your project compile correctly without io-ts-transformer?

**Comment by awerlogus** [comment]
Or you're talking about this file https://github.com/awerlogus/io-ts-transformer/blob/master/index.js?

**Comment by sammoh94** [comment]
Sorry didn't realize it was empty here. The code is compiling correctly. The overarching issue was that when I run the code, I get a TypeError that says buildDecoder is not a function. Here is my code:

```
import { buildDecoder } from 'io-ts-transformer';

type Channel = {
  name: string;
  payload: {
    meta: string;
    prop: number[];
    mappings: Map<number, string>;
    nested: {
      levelOne: string;
      properties: {
        nestedKey: string;
      };
      maybeProperty?: number;
      maybeMappings?: {
        mappingName: string;
        mappingValue: number;
      };
    };
  };
};

const channelType = buildDecoder<Channel>();
console.log(channelType);
```

I changed the import to be `import * as t from io-ts-transformer` and logged `t`. That resulted in an empty object which explains the error above

**Comment by awerlogus** [comment]
Looks like you have not registered the transformer in your compiler.
https://github.com/awerlogus/io-ts-transformer#how-to-use-the-custom-transformer

P.S. I am not sure the Map structure will be transformed correctly. As far as I remember, the basic version of io-ts does not support it.

**Comment by awerlogus** [comment]
Do you still have any problems? Can I close this issue?
